<a href="https://colab.research.google.com/github/itikatyagi/Pytorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [29]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [7]:
## Add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [8]:
## Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [9]:
## subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [10]:
## sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [11]:
## multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
## mul function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
## Divide
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
## Divide function
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
## Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [17]:
## Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [18]:
## Exponents/Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [22]:
## Another way to write add
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a

tensor([1, 2, 3, 4])

In [31]:
## Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [32]:
tensor_a

tensor([1, 2, 3, 4])

In [34]:
tensor_a = tensor_a + tensor_b
##tensor_a.add_(tensor_b)

In [35]:
tensor_a

tensor([11, 14, 17, 20])